### PR TITLE
Greatly simplified reddit integration in imgur.js

### PR DESCRIPTION
**Pull request by tetris-11**
Hi, I just did a quick fix of _imgur.js_  that removes a lot of unneccesary code I added earlier and integrates much better with your original code base.

This also fixed the album issue I was having with some subreddits.

(Last edit I swear!)

### CODE REVIEW

**Comment by walokra** [comment]
Released 0.9.0 with the new subreddit mode. Available now from OpenRepos, later from Harbour.

**Comment by tetris-11** [comment]
Excellent, you cleaned up my messy search integration too - much appreciated.

The floating subreddit TextField really should be fixed into the main column somehow. I wish I could help bit Silica is still a mystery to me.

Also, maybe it would benefit from being a text editable dropdown menu of previous searches? 

Either way, thanks.

**Comment by walokra** [comment]
Thanks for the pull request, most of the work was already done :)

I thought about the floating TextField but decided to leave it where it was as the main column gets crowded. Will see how it works like that.

Storing the previous searches is good idea.

**Comment by tetris-11** [comment]
It's a really great app -- can't wait to see future updates :-)

**Pull request merged**
